# Generated by Django 4.2 on 2023-04-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profilemodel_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
