# Generated by Django 4.2 on 2023-04-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profilemodel_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
